Controllers/ProductosOKController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppPRODUCTOS.Models;
using WebAppPRODUCTOS.ViewsModels;

namespace WebAppPRODUCTOS.Controllers
{
    public class ProductosOKController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment env;

        public ProductosOKController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            this.env = env;
        }

        // GET: ProductosOK
        public async Task<IActionResult> Index(string busquedaNombre,int? categoriaId, int? marcaId, int?id, int? proveedorId)
        {


            var applicationDbContext = _context.productos.Include(p => p.categoria).Select(p=>p).Include(p => p.marca).Select(p => p);
            if (!string.IsNullOrEmpty(busquedaNombre))
            {
                applicationDbContext = applicationDbContext.Where(p => p.nombres.Contains(busquedaNombre));//genero una query con filtros que se ejecuta el return 
            }
            if (categoriaId.HasValue)//has value=valida que tenga un valor el entero
            {
                applicationDbContext = applicationDbContext.Where(p => p.categoriaId == categoriaId.Value);
            }
            if (marcaId.HasValue)//has value=valida que tenga un valor el entero
            {
                applicationDbContext = applicationDbContext.Where(p => p.marcaId == marcaId.Value);//me filtre por id de carrera
            }

            ProductosViewModel modelo = new ProductosViewModel()//creamos el objeto para asignarle las prop
            {
                Productos = applicationDbContext.ToList(),
                Marcas = new SelectList(_context.marcas, "Id", "descripcion", marcaId),
                Categorias = new SelectList(_context.categorias, "Id", "descripcion", categoriaId),
                nombre = busquedaNombre,
            };

            return View(modelo);
        }

        //public async Task<IActionResult> Proveedores(int? id) 
        //{
        //    var applicationDbContext = _context.proveedoresProductos.Where(x => x.Id == id);
        //    var model = await applicationDbContext.Select(x => x.proveedorId).ToListAsync();
        //    var lista = _context.proveedores.Where(x => model.Contains(x.Id));


        //    ViewData["proveedoresProducto"] = new MultiSelectList(lista, "Id", "Nombre");
        //    return View();
        //}

// GET: ProductosOK/Details/5
public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.productos
                .Include(p => p.categoria)
                .Include(p => p.marca)
                .Include(p=>p.proveedoresProductos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        [Authorize]
        // GET: ProductosOK/Create
        public IActionResult Create()
        {
            ViewData["proveedorId"] = new MultiSelectList(_context.proveedoresProductos, "proveedorId", "nombres");
            ViewData["categoriaId"] = new SelectList(_context.categorias, "Id", "descripcion");
            ViewData["marcaId"] = new SelectList(_context.marcas, "Id", "descripcion");
            return View();
        }

        // POST: ProductosOK/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,nombres,precio,descripcion,imagen,favorito,categoriaId,marcaId")] Producto producto)
        {
            if (ModelState.IsValid)//verifica las etiquetas de nuestro modelo: si es requerido, si cumple con el rango, etc
            {
                var archivos = HttpContext.Request.Form.Files;//httpcontext -> es la clase que permite capturar los achivos que se envian a traves del form web
                if (archivos != null && archivos.Count > 0) //como es archivoos=coleccion accedemos a los elementos
                {
                    var archivoFoto = archivos[0];//accedemos al archivo unico 

                    if (archivoFoto.Length > 0) //si hay contenido
                    {
                        var pathDestino = Path.Combine(env.WebRootPath, "images");//concatena la ruta (string) es necesario definir el env (al principio esta)
                        //genera un nombre aleatorio del archivo destino fotografia
                        var archivoDestino = Guid.NewGuid().ToString()//guid->genera un hash aleatorio
                            .Replace("-", "") + Path.GetExtension(archivoFoto.FileName); //concatenamos la extención del archivo
                        var rutaDestino = Path.Combine(pathDestino, archivoDestino);//concatenamos el pathdestino y el archivodestino

                        using (var filestream = new FileStream(rutaDestino, FileMode.Create))//using -> cuando termina libera los recursos usados
                        {
                            archivoFoto.CopyTo(filestream);
                            producto.imagen = archivoDestino;
                        };

                    }

                }

                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["proveedorId"] = new SelectList(_context.proveedoresProductos, "Id", "Id", producto.proveedoresProductos);
            ViewData["categoriaId"] = new SelectList(_context.categorias, "Id", "Id", producto.categoriaId);
            ViewData["marcaId"] = new SelectList(_context.marcas, "Id", "Id", producto.marcaId);
            return View(producto);
        }

        // GET: ProductosOK/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["proveedorId"] = new SelectList(_context.proveedoresProductos, "Id", "Id", producto.proveedoresProductos);
            ViewData["categoriaId"] = new SelectList(_context.categorias, "Id", "descripcion", producto.categoriaId);
            ViewData["marcaId"] = new SelectList(_context.marcas, "Id", "descripcion", producto.marcaId);
            return View(producto);
        }

        // POST: ProductosOK/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nombres,precio,descripcion,imagen,favorito,categoriaId,marcaId")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var archivos = HttpContext.Request.Form.Files;
                if (archivos != null && archivos.Count > 0)
                {
                    var archivoFoto = archivos[0];
                    if (archivoFoto.Length > 0)
                    {
                        var pathDestino = Path.Combine(env.WebRootPath, "images");
                        var archivoDestino = Guid.NewGuid().ToString()//guid->genera un hash aleatorio
                            .Replace("-", "") + Path.GetExtension(archivoFoto.FileName); //concatenamos la extención del archivo
                        var rutaDestino = Path.Combine(pathDestino, archivoDestino);//concatenamos el pathdestino y el archivodestino

                        if (!string.IsNullOrEmpty(producto.imagen)) //para revisar si habia foto precargada y no se rompa
                        {
                            //si existe una foto anterior se elimine
                            string fotoAnterior = Path.Combine(pathDestino, producto.imagen);
                            if (System.IO.File.Exists(fotoAnterior))
                            {
                                System.IO.File.Delete(fotoAnterior);
                            }
                        }

                        using (var filestream = new FileStream(rutaDestino, FileMode.Create))//using -> cuando termina libera los recursos usados
                        {
                            archivoFoto.CopyTo(filestream);
                            producto.imagen = archivoDestino;
                        };

                    }
                }
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["proveedorId"] = new SelectList(_context.proveedoresProductos, "Id", "Id", producto.proveedoresProductos);

Controllers/ProveedoresOKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppPRODUCTOS.Models;

namespace WebAppPRODUCTOS.Controllers
{
    public class ProveedoresOKController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProveedoresOKController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProveedoresOK
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.proveedores.ToListAsync());
        }

        // GET: ProveedoresOK/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.proveedores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proveedor == null)
            {
                return NotFound();
            }

            return View(proveedor);
        }

        // GET: ProveedoresOK/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProveedoresOK/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,nombres,telefono,domicilio,localidad,provincia")] Proveedor proveedor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proveedor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proveedor);
        }

        // GET: ProveedoresOK/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.proveedores.FindAsync(id);
            if (proveedor == null)
            {
                return NotFound();
            }
            return View(proveedor);
        }

        // POST: ProveedoresOK/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nombres,telefono,domicilio,localidad,provincia")] Proveedor proveedor)
        {
            if (id != proveedor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proveedor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProveedorExists(proveedor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proveedor);
        }

        // GET: ProveedoresOK/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.proveedores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proveedor == null)
            {
                return NotFound();
            }

            return View(proveedor);
        }

        // POST: ProveedoresOK/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proveedor = await _context.proveedores.FindAsync(id);
            _context.proveedores.Remove(proveedor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProveedorExists(int id)
        {
            return _context.proveedores.Any(e => e.Id == id);
        }
    }
}

Views/ProductosOK/Create.cshtml
@model WebAppPRODUCTOS.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombres" class="control-label"></label>
                <input asp-for="nombres" class="form-control" />
                <span asp-validation-for="nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img src="" id="imagen2" class="img-thumbnail"
                     style="max-height: 75px;max-width: 75px;"
                     asp-append-version="true" />
                <label class="control-label">Seleccione fotografia</label>
                <input asp-for="imagen" type="file" id="seleccionImg">@*para que solo acepte un tipo de archivos -> accept="image/jpeg"*@
                <input hidden asp-for="imagen" id="imagenHidden" />
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="favorito" /> @Html.DisplayNameFor(model => model.favorito)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="categoriaId" class="control-label"></label>
                <select asp-for="categoriaId" class="form-control" asp-items="ViewBag.categoriaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="marcaId" class="control-label"></label>
                <select asp-for="marcaId" class="form-control" asp-items="ViewBag.marcaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

        <script>
            seleccionImg.onchange = evt => {
                const [file] = seleccionImg.files
                if (file) {
                    imagen2.src = URL.createObjectURL(file)
                    //imagen2.removeAttribute("hidden");
                    imagenHidden.value = file.name;
                }

            }

        </script>
}

Views/ProductosOK/Delete.cshtml
@model WebAppPRODUCTOS.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
        <dd>
            @if (!string.IsNullOrEmpty(@Model.imagen))
            {
                <img src="~/images/@Model.imagen" class="img-thumbnail"
                     style="max-height:75px; max-width:75px;" asp-append-version="true" />
            }
        </dd>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nombres)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nombres)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.favorito)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.favorito)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.categoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.categoria.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.marca.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ProductosOK/Details.cshtml
@model WebAppPRODUCTOS.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
        <dt>
            @*Agregamos la imagen al details arriba de todo*@
            @if (!string.IsNullOrEmpty(@Model.imagen))
            {
                <img src="~/images/@Model.imagen" class="img-thumbnail"
                     style="max-height:75px; max-width:75px;" asp-append-version="true" />
            }
        </dt>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.nombres)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.nombres)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.precio)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.precio)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.descripcion)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.favorito)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.favorito)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.categoria)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.categoria.descripcion)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.marca)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.marca.descripcion)
            </dd>
            <dt class="col-sm-2">
                Proveedores
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.proveedoresProductos)
            </dd>
        </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ProductosOK/Edit.cshtml
@model WebAppPRODUCTOS.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="nombres" class="control-label"></label>
                <input asp-for="nombres" class="form-control" />
                <span asp-validation-for="nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio" class="control-label"></label>
                <input asp-for="precio" class="form-control" />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="imagen" />@*ocualtar el dato de la foto para poder recibirla*@
                <img src="~/images/@Model.imagen" id="imagen2" class="img-thumbnail"
                     style="max-height: 75px;max-width: 75px;"
                     display=@(!string.IsNullOrEmpty(@Model.imagen) ? "block" : "none") asp-append-version="true" />
                @* Si no es vacia el nombre de la foto muestra el display block sino muestra el none que es vacia *@
                <label class="control-label">Seleccione fotografia</label>
                <input asp-for="imagen" type="file" id="seleccionImg" />
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="favorito" /> @Html.DisplayNameFor(model => model.favorito)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="categoriaId" class="control-label"></label>
                <select asp-for="categoriaId" class="form-control" asp-items="ViewBag.categoriaId"></select>
                <span asp-validation-for="categoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="marcaId" class="control-label"></label>
                <select asp-for="marcaId" class="form-control" asp-items="ViewBag.marcaId"></select>
                <span asp-validation-for="marcaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="proveedoresProductos" class="control-label"></label>
                <input asp-for="proveedoresProductos" class="form-control" />
                <span asp-validation-for="proveedoresProductos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js//preview.js"></script>
    @* Importamos libreria de jquery y el archivo preview.js *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

}

Views/ProductosOK/Index.cshtml
@model WebAppPRODUCTOS.ViewsModels.ProductosViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Productos</h1>
<br />  
<p>
    <a asp-action="Create" class="btn btn-dark text-md-right">Crear Nuevo Producto</a>
</p>
@*Creamos el filtro de busqueda*@ @*viewbag para que nos traiga el listado de carreras*@
<form asp-action="Index" method="get">
    <nav class="navbar navbar-dark bg-secondary text-white text-sm-left">
        <form class="form-inline">
            <a class="navbar-brand">
                Nombre: <input type="text" asp-for="@Model.nombre" name="busquedaNombre" value="" />
            </a>
            <a class="navbar-brand">
                Categoria:
                <select class="form-select text-center" name="categoriaId" asp-items="@Model.Categorias">
                    <option value="">Todas</option>
                </select>
            </a>
            <a class="navbar-brand">
                Marca:
                <select class="form-select text-center" name="marcaId" asp-items="@Model.Marcas">
                    <option value="">Todas</option>
                </select>
            </a>
            <button type="submit" class="btn btn-primary text-md-right" value="Filtrar">Filtrar</button>
            <a asp-action="Index" class="btn btn-secondary text-md-right">Volver a la lista completa</a>

        </form>
    </nav>
    <br />
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].nombres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].favorito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productos[0].marca)
            </th>
            <th>
                Proveedores
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Productos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombres)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @if (!string.IsNullOrEmpty(@item.imagen))//si no es nulo o vacio
                    {
                        <img src="~/images/@item.imagen" class="img-thumbnail"
                             style="max-height:75px; max-width:75px;" asp-append-version="true" />
                    }
                    @* img-thumbail-> sirve para que tome el tamaño de una previsulaizacion ->boostrap *@
                    @* asp-append-version-> si la img cambia se actualice el nombre y la imagen el el navegador*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.favorito)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoria.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.marca.descripcion)
                </td>
                <td>
                    @*@foreach (var item in ProveedoresProducto)
                    {
                             @Html.(ModelItem => item.proveedoresProductos)

                    }*@
                    <a href="@Url.Action("Index","ProveedoresOK")">ver proveedores</a>
                    @*<a href="@Url.Action("Proveedores","ProductosOK",new { id=item.Id})">ver proveedor</a>*@
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>